// ============================================================================
// NLAMS PUBLIC JURY DEMO DATASET
// 100% Synthetic Demo Records — Safe for Public Unauthenticated Demonstration
// Focus: SM-NASHIK-DEMO-01 (Mumbai–Nagpur Samruddhi Expressway — Nashik Corridor)
// ============================================================================

export interface DemoProject {
  id: string
  project_code: string
  project_name: string
  state: string
  district: string
  department: string
  acquiring_authority?: string
  project_type: string
  corridor_length_km: number
  total_area_required_ha: number
  status: string
  review_status: string
  gis_file_url: string | null
  description: string
}

export interface DemoParcel {
  id: string
  project_id: string
  project_code: string
  parcel_number: string
  parcel_no: string
  owner_name: string
  village_name: string
  taluka_name: string
  tehsil: string
  district: string
  state: string
  survey_number: string
  survey_no: string
  khasra_no: string
  land_type: string
  notified_area_sqm: number
  affected_area_sqm: number
  possession_status: string
  field_verification_status: string
  field_verified_at: string | null
  field_verified_by: string | null
  field_remarks: string | null
  compensation_amount: number
  compensation_assessed: number
  compensation_approved: number
  compensation_paid: number
  payment_status: string
  payment_reference: string | null
  payment_released_at: string | null
  rehabilitation_status: string
  rehabilitation_amount: number
  rehabilitation_remarks: string | null
  rehabilitation_completed_at: string | null
  latitude: number
  longitude: number
}

export interface DemoWorkflow {
  id: string
  project_code: string
  land_parcel_id?: string | null
  workflow_type: string
  stage_name: string
  status: 'Approved' | 'Pending Approval' | 'In Progress' | 'Draft'
  assigned_to: string
  submitted_by: string
  approved_by: string | null
  remarks: string
  created_at: string
  approved_at: string | null
}

export interface DemoAssignment {
  id: string
  parcel_id: string
  parcel_number: string
  owner_name: string
  village_name: string
  assigned_officer_id: string
  assigned_officer_name: string
  assigned_officer_email: string
  assigned_at: string
  status: 'Completed' | 'Pending' | 'In Progress'
  priority: 'High' | 'Medium' | 'Low'
  due_date: string
  remarks: string
}

export interface DemoObjection {
  id: string
  parcel_id: string
  parcel_number: string
  village_name: string
  survey_number: string
  owner_name: string
  objection_type: string
  description: string
  status: 'Submitted' | 'Under Review' | 'Resolved' | 'Rejected'
  submitted_at: string
  reviewed_at: string | null
  resolved_at: string | null
  reviewer_name: string | null
  resolution_remarks: string | null
}

export interface DemoEvidenceDoc {
  id: string
  parcel_id: string
  file_name: string
  file_type: string
  file_size_bytes: number
  description: string
  uploaded_by: string
  created_at: string
  category: 'Boundary Marker' | 'Cadastral Survey' | 'Tree Valuation' | 'DBT Receipt' | 'Gazette Notice'
}

export const DEMO_PROJECTS: DemoProject[] = [
  {
    "id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "project_name": "Mumbai–Nagpur Samruddhi Expressway — Nashik Corridor Demo",
    "state": "Maharashtra",
    "district": "Nashik",
    "department": "Ministry of Road Transport & Highways",
    "acquiring_authority": "NHAI – National Highways Authority of India",
    "project_type": "National Highway",
    "corridor_length_km": 39.92,
    "total_area_required_ha": 97.48,
    "status": "Active",
    "review_status": "Approved",
    "gis_file_url": "/gis/SM-NASHIK-DEMO-01.geojson",
    "description": "Demonstration corridor for Mumbai–Nagpur Samruddhi Expressway in Nashik District comprising 24 synthetic demo land parcels."
  },
  {
    "id": "f1abc9f1-f85c-4d22-996c-19a2012207b5",
    "project_code": "NHAI-DEL-BOM-01",
    "project_name": "Delhi–Mumbai Expressway Corridor",
    "state": "Delhi / Rajasthan / Gujarat / Maharashtra",
    "district": "Multi-District Corridor",
    "department": "Ministry of Road Transport & Highways",
    "acquiring_authority": "NHAI – National Highways Authority of India",
    "project_type": "Expressway",
    "corridor_length_km": 1350,
    "total_area_required_ha": 8120.65,
    "status": "Active",
    "review_status": "Approved",
    "gis_file_url": null,
    "description": "Flagship Greenfield 8-lane expressway connecting Delhi National Capital Region to Mumbai."
  },
  {
    "id": "fafbcc4b-ad14-4b8e-ae27-d276a5916adc",
    "project_code": "NHAI-NSK-SURCHE",
    "project_name": "Nashik–Surat Economic Highway",
    "state": "Maharashtra / Gujarat",
    "district": "Nashik Division",
    "department": "Ministry of Road Transport & Highways",
    "acquiring_authority": "NHAI – National Highways Authority of India",
    "project_type": "Economic Corridor",
    "corridor_length_km": 290.5,
    "total_area_required_ha": 3450.5,
    "status": "Active",
    "review_status": "Approved",
    "gis_file_url": null,
    "description": "Inter-state economic corridor strengthening industrial logistics between Nashik manufacturing zone and Surat port cluster."
  },
  {
    "id": "434869ce-0cb4-4a31-9339-04402a91a28f",
    "project_code": "NH-334B",
    "project_name": "Rampur–Baghpat Expressway Corridor",
    "state": "Uttar Pradesh",
    "district": "Meerut Division",
    "department": "National Highways Authority of India",
    "project_type": "National Highway",
    "corridor_length_km": 115,
    "total_area_required_ha": 1280,
    "status": "Under Review",
    "review_status": "Under Review",
    "gis_file_url": null,
    "description": "Strategic highway link bypassing congested peri-urban centers in Western UP."
  },
  {
    "id": "1e7c48b0-a0e1-4432-83c8-6248d59028c9",
    "project_code": "NH-709A",
    "project_name": "Kishanganj Bypass Realignment",
    "state": "Bihar / UP Periphery",
    "district": "Muzaffarnagar",
    "department": "State Public Works Department",
    "project_type": "Bypass / Alignment",
    "corridor_length_km": 45.8,
    "total_area_required_ha": 650.25,
    "status": "Draft",
    "review_status": "Draft",
    "gis_file_url": null,
    "description": "Bypass realigning critical bottleneck zones around regional grain markets."
  },
  {
    "id": "5e0cbc8f-517a-4a3a-8c10-eb8430a0cdfc",
    "project_code": "EW-14",
    "project_name": "Eastern Freight & Logistics Spur",
    "state": "Uttar Pradesh",
    "district": "Bulandshahr",
    "department": "Dedicated Freight Corridor Corp of India",
    "project_type": "Freight Corridor",
    "corridor_length_km": 210.4,
    "total_area_required_ha": 2400,
    "status": "Active",
    "review_status": "Approved",
    "gis_file_url": null,
    "description": "High-speed multimodal freight artery connecting hinterland industrial parks to coastal corridors."
  }
];

export const DEMO_PARCELS: DemoParcel[] = [
  {
    "id": "demo-parcel-101",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-101",
    "parcel_no": "SM-NK-101",
    "owner_name": "Eknath Balwantrao Shinde (DEMO-101)",
    "village_name": "Vihigaon",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-101/A",
    "survey_no": "SY-101/A",
    "khasra_no": "KHS-SM-101",
    "land_type": "Agricultural",
    "notified_area_sqm": 263250,
    "affected_area_sqm": 19968.58,
    "possession_status": "Possession Taken",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Ground survey verified. Highway boundary stones demarcated.",
    "compensation_amount": 12979577,
    "compensation_assessed": 12979577,
    "compensation_approved": 12979577,
    "compensation_paid": 12979577,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8000",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.769918,
    "longitude": 73.789561
  },
  {
    "id": "demo-parcel-102",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-102",
    "parcel_no": "SM-NK-102",
    "owner_name": "Vishwanath Pandurang Jadhav (DEMO-102)",
    "village_name": "Kasarwadi",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-102/B",
    "survey_no": "SY-102/B",
    "khasra_no": "KHS-SM-102",
    "land_type": "Orchard",
    "notified_area_sqm": 348347.37,
    "affected_area_sqm": 36380.35,
    "possession_status": "Acquired",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Joint measurement survey completed. Solatium paid.",
    "compensation_amount": 23647228,
    "compensation_assessed": 23647228,
    "compensation_approved": 23647228,
    "compensation_paid": 23647228,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8001",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "In Progress",
    "rehabilitation_amount": 250000,
    "rehabilitation_remarks": "Livelihood assistance in progress.",
    "rehabilitation_completed_at": null,
    "latitude": 19.780653,
    "longitude": 73.801558
  },
  {
    "id": "demo-parcel-103",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-103",
    "parcel_no": "SM-NK-103",
    "owner_name": "Sunita Dnyaneshwar Bhor (DEMO-103)",
    "village_name": "Wadivarhe",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-103/C",
    "survey_no": "SY-103/C",
    "khasra_no": "KHS-SM-103",
    "land_type": "Agricultural",
    "notified_area_sqm": 446286.19,
    "affected_area_sqm": 31866.37,
    "possession_status": "Completed",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Full compensation and R&R entitlement cleared.",
    "compensation_amount": 20713141,
    "compensation_assessed": 20713141,
    "compensation_approved": 20713141,
    "compensation_paid": 20713141,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8002",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.783741,
    "longitude": 73.817855
  },
  {
    "id": "demo-parcel-104",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-104",
    "parcel_no": "SM-NK-104",
    "owner_name": "Dattatray Ramchandra Gaikwad (DEMO-104)",
    "village_name": "Gondedumala",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-104/D",
    "survey_no": "SY-104/D",
    "khasra_no": "KHS-SM-104",
    "land_type": "Residential fringe",
    "notified_area_sqm": 543965.5,
    "affected_area_sqm": 57070.75,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Award determined under Section 23. Disbursal pending.",
    "compensation_amount": 37095988,
    "compensation_assessed": 37095988,
    "compensation_approved": 37095988,
    "compensation_paid": 0,
    "payment_status": "Approved",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Eligible",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.794963,
    "longitude": 73.829629
  },
  {
    "id": "demo-parcel-105",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-105",
    "parcel_no": "SM-NK-105",
    "owner_name": "Kashinath Shivram Gite (DEMO-105)",
    "village_name": "Bharvir Khurd",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-105/A",
    "survey_no": "SY-105/A",
    "khasra_no": "KHS-SM-105",
    "land_type": "Agricultural",
    "notified_area_sqm": 630787.36,
    "affected_area_sqm": 29774.23,
    "possession_status": "Pending",
    "field_verification_status": "Needs Review",
    "field_verified_at": "2026-09-12T14:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Heirship partition claim submitted; pending revenue review.",
    "compensation_amount": 19353250,
    "compensation_assessed": 19353250,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.797166,
    "longitude": 73.846247
  },
  {
    "id": "demo-parcel-106",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-106",
    "parcel_no": "SM-NK-106",
    "owner_name": "Anand Raoji Sangale (DEMO-106)",
    "village_name": "Bharvir Budruk",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-106/B",
    "survey_no": "SY-106/B",
    "khasra_no": "KHS-SM-106",
    "land_type": "Orchard",
    "notified_area_sqm": 794861.93,
    "affected_area_sqm": 55936.57,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Field verification complete. Bank account validated on PFMS.",
    "compensation_amount": 36358771,
    "compensation_assessed": 36358771,
    "compensation_approved": 36358771,
    "compensation_paid": 0,
    "payment_status": "Payment Pending",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Eligible",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.809476,
    "longitude": 73.857507
  },
  {
    "id": "demo-parcel-107",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-107",
    "parcel_no": "SM-NK-107",
    "owner_name": "Pramod Vasantrao Chavan (DEMO-107)",
    "village_name": "Shivajinagar",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-107/C",
    "survey_no": "SY-107/C",
    "khasra_no": "KHS-SM-107",
    "land_type": "Agricultural",
    "notified_area_sqm": 457140.48,
    "affected_area_sqm": 18390.8,
    "possession_status": "Possession Taken",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Possession handed over to NHAI project director.",
    "compensation_amount": 11954020,
    "compensation_assessed": 11954020,
    "compensation_approved": 11954020,
    "compensation_paid": 11954020,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8006",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.810267,
    "longitude": 73.874734
  },
  {
    "id": "demo-parcel-108",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-108",
    "parcel_no": "SM-NK-108",
    "owner_name": "Shantabai Madhavrao Dhikale (DEMO-108)",
    "village_name": "Mundhegaon",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-108/D",
    "survey_no": "SY-108/D",
    "khasra_no": "KHS-SM-108",
    "land_type": "Residential fringe",
    "notified_area_sqm": 331990.71,
    "affected_area_sqm": 42968.04,
    "possession_status": "Pending",
    "field_verification_status": "Pending",
    "field_verified_at": null,
    "field_verified_by": null,
    "field_remarks": "Awaiting village joint inspection date.",
    "compensation_amount": 27929226,
    "compensation_assessed": 27929226,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Not Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.821577,
    "longitude": 73.886553
  },
  {
    "id": "demo-parcel-109",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-109",
    "parcel_no": "SM-NK-109",
    "owner_name": "Bhagwan Trimbak Kokate (DEMO-109)",
    "village_name": "Vihigaon",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-109/A",
    "survey_no": "SY-109/A",
    "khasra_no": "KHS-SM-109",
    "land_type": "Agricultural",
    "notified_area_sqm": 405783.5,
    "affected_area_sqm": 30390.94,
    "possession_status": "Acquired",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Tree and borewell valuation approved.",
    "compensation_amount": 19754111,
    "compensation_assessed": 19754111,
    "compensation_approved": 19754111,
    "compensation_paid": 19754111,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8008",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.824668,
    "longitude": 73.902645
  },
  {
    "id": "demo-parcel-110",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-110",
    "parcel_no": "SM-NK-110",
    "owner_name": "Sambhaji Namdeo Bodke (DEMO-110)",
    "village_name": "Kasarwadi",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-110/B",
    "survey_no": "SY-110/B",
    "khasra_no": "KHS-SM-110",
    "land_type": "Orchard",
    "notified_area_sqm": 497144.93,
    "affected_area_sqm": 56981.82,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Verification cleared without encumbrance.",
    "compensation_amount": 37038183,
    "compensation_assessed": 37038183,
    "compensation_approved": 37038183,
    "compensation_paid": 0,
    "payment_status": "Approved",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "In Progress",
    "rehabilitation_amount": 250000,
    "rehabilitation_remarks": "Livelihood assistance in progress.",
    "rehabilitation_completed_at": null,
    "latitude": 19.835464,
    "longitude": 73.914736
  },
  {
    "id": "demo-parcel-111",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-111",
    "parcel_no": "SM-NK-111",
    "owner_name": "Chandrakant Motiram Khule (DEMO-111)",
    "village_name": "Wadivarhe",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-111/C",
    "survey_no": "SY-111/C",
    "khasra_no": "KHS-SM-111",
    "land_type": "Agricultural",
    "notified_area_sqm": 639268.56,
    "affected_area_sqm": 37856.11,
    "possession_status": "Pending",
    "field_verification_status": "Needs Review",
    "field_verified_at": "2026-09-12T14:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Boundary discrepancy noted against adjacent canal spur.",
    "compensation_amount": 24606472,
    "compensation_assessed": 24606472,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.837759,
    "longitude": 73.931338
  },
  {
    "id": "demo-parcel-112",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-112",
    "parcel_no": "SM-NK-112",
    "owner_name": "Ravindra Popatrao Wagh (DEMO-112)",
    "village_name": "Gondedumala",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-112/D",
    "survey_no": "SY-112/D",
    "khasra_no": "KHS-SM-112",
    "land_type": "Residential fringe",
    "notified_area_sqm": 772148.58,
    "affected_area_sqm": 67615.3,
    "possession_status": "Possession Taken",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Formal possession receipt executed with village Talathi.",
    "compensation_amount": 43949945,
    "compensation_assessed": 43949945,
    "compensation_approved": 43949945,
    "compensation_paid": 43949945,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8011",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.848796,
    "longitude": 73.94369
  },
  {
    "id": "demo-parcel-113",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-113",
    "parcel_no": "SM-NK-113",
    "owner_name": "Babasaheb Kisan Avhad (DEMO-113)",
    "village_name": "Bharvir Khurd",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-113/A",
    "survey_no": "SY-113/A",
    "khasra_no": "KHS-SM-113",
    "land_type": "Agricultural",
    "notified_area_sqm": 422846.72,
    "affected_area_sqm": 16919.18,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Section 19 declaration notified.",
    "compensation_amount": 10997467,
    "compensation_assessed": 10997467,
    "compensation_approved": 10997467,
    "compensation_paid": 0,
    "payment_status": "Payment Pending",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Eligible",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.848214,
    "longitude": 73.960657
  },
  {
    "id": "demo-parcel-114",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-114",
    "parcel_no": "SM-NK-114",
    "owner_name": "Nirmala Ramdas Jagtap (DEMO-114)",
    "village_name": "Bharvir Budruk",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-114/B",
    "survey_no": "SY-114/B",
    "khasra_no": "KHS-SM-114",
    "land_type": "Orchard",
    "notified_area_sqm": 536809.96,
    "affected_area_sqm": 42640.19,
    "possession_status": "Pending",
    "field_verification_status": "Pending",
    "field_verified_at": null,
    "field_verified_by": null,
    "field_remarks": "Initial notice served to landholder.",
    "compensation_amount": 27716124,
    "compensation_assessed": 27716124,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Not Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.859606,
    "longitude": 73.973232
  },
  {
    "id": "demo-parcel-115",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-115",
    "parcel_no": "SM-NK-115",
    "owner_name": "Suresh Ganpat Sonawane (DEMO-115)",
    "village_name": "Shivajinagar",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-115/C",
    "survey_no": "SY-115/C",
    "khasra_no": "KHS-SM-115",
    "land_type": "Agricultural",
    "notified_area_sqm": 388094.03,
    "affected_area_sqm": 30510.76,
    "possession_status": "Acquired",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Agricultural land compensation credited via DBT.",
    "compensation_amount": 19831994,
    "compensation_assessed": 19831994,
    "compensation_approved": 19831994,
    "compensation_paid": 19831994,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8014",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "In Progress",
    "rehabilitation_amount": 250000,
    "rehabilitation_remarks": "Livelihood assistance in progress.",
    "rehabilitation_completed_at": null,
    "latitude": 19.858853,
    "longitude": 73.990355
  },
  {
    "id": "demo-parcel-116",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-116",
    "parcel_no": "SM-NK-116",
    "owner_name": "Gorakhnath Bhaurao Pingle (DEMO-116)",
    "village_name": "Mundhegaon",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-116/D",
    "survey_no": "SY-116/D",
    "khasra_no": "KHS-SM-116",
    "land_type": "Residential fringe",
    "notified_area_sqm": 499517.03,
    "affected_area_sqm": 52521.85,
    "possession_status": "Completed",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "All statutory requirements fulfilled.",
    "compensation_amount": 34139203,
    "compensation_assessed": 34139203,
    "compensation_approved": 34139203,
    "compensation_paid": 34139203,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8015",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.867679,
    "longitude": 74.004107
  },
  {
    "id": "demo-parcel-117",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-117",
    "parcel_no": "SM-NK-117",
    "owner_name": "Murlidhar Hari Sanap (DEMO-117)",
    "village_name": "Vihigaon",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-117/A",
    "survey_no": "SY-117/A",
    "khasra_no": "KHS-SM-117",
    "land_type": "Agricultural",
    "notified_area_sqm": 585993.95,
    "affected_area_sqm": 36063.57,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Field evidence photos and GPS boundary logged.",
    "compensation_amount": 23441321,
    "compensation_assessed": 23441321,
    "compensation_approved": 23441321,
    "compensation_paid": 0,
    "payment_status": "Approved",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Eligible",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.867305,
    "longitude": 74.020744
  },
  {
    "id": "demo-parcel-118",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-118",
    "parcel_no": "SM-NK-118",
    "owner_name": "Indubai Janardan Gade (DEMO-118)",
    "village_name": "Kasarwadi",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-118/B",
    "survey_no": "SY-118/B",
    "khasra_no": "KHS-SM-118",
    "land_type": "Orchard",
    "notified_area_sqm": 710862.71,
    "affected_area_sqm": 64291.68,
    "possession_status": "Possession Taken",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Demarcation completed with stone pillars.",
    "compensation_amount": 41789592,
    "compensation_assessed": 41789592,
    "compensation_approved": 41789592,
    "compensation_paid": 41789592,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8017",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.876375,
    "longitude": 74.034687
  },
  {
    "id": "demo-parcel-119",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-119",
    "parcel_no": "SM-NK-119",
    "owner_name": "Ashok Nivrutti Mogal (DEMO-119)",
    "village_name": "Wadivarhe",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-119/C",
    "survey_no": "SY-119/C",
    "khasra_no": "KHS-SM-119",
    "land_type": "Agricultural",
    "notified_area_sqm": 411949.12,
    "affected_area_sqm": 16342.46,
    "possession_status": "Pending",
    "field_verification_status": "Needs Review",
    "field_verified_at": "2026-09-12T14:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Tenancy verification pending with Tehsildar office.",
    "compensation_amount": 10622599,
    "compensation_assessed": 10622599,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.874504,
    "longitude": 74.051529
  },
  {
    "id": "demo-parcel-120",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-120",
    "parcel_no": "SM-NK-120",
    "owner_name": "Deepak Yashwant Kadam (DEMO-120)",
    "village_name": "Gondedumala",
    "taluka_name": "Igatpuri Taluka",
    "tehsil": "Igatpuri Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-120/D",
    "survey_no": "SY-120/D",
    "khasra_no": "KHS-SM-120",
    "land_type": "Residential fringe",
    "notified_area_sqm": 524670.27,
    "affected_area_sqm": 44863.74,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Valuation report submitted to SLAO.",
    "compensation_amount": 29161431,
    "compensation_assessed": 29161431,
    "compensation_approved": 29161431,
    "compensation_paid": 0,
    "payment_status": "Payment Pending",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Eligible",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.884578,
    "longitude": 74.065091
  },
  {
    "id": "demo-parcel-121",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-121",
    "parcel_no": "SM-NK-121",
    "owner_name": "Uttam Dashrath Darade (DEMO-121)",
    "village_name": "Bharvir Khurd",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-121/A",
    "survey_no": "SY-121/A",
    "khasra_no": "KHS-SM-121",
    "land_type": "Agricultural",
    "notified_area_sqm": 366064.32,
    "affected_area_sqm": 31918.72,
    "possession_status": "Acquired",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "DBT transfer successful. No grievances pending.",
    "compensation_amount": 20747168,
    "compensation_assessed": 20747168,
    "compensation_approved": 20747168,
    "compensation_paid": 20747168,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8020",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.883768,
    "longitude": 74.08185
  },
  {
    "id": "demo-parcel-122",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-122",
    "parcel_no": "SM-NK-122",
    "owner_name": "Parvatibai Shankar Tile (DEMO-122)",
    "village_name": "Bharvir Budruk",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-122/B",
    "survey_no": "SY-122/B",
    "khasra_no": "KHS-SM-122",
    "land_type": "Orchard",
    "notified_area_sqm": 454280.48,
    "affected_area_sqm": 48338.64,
    "possession_status": "Pending",
    "field_verification_status": "Pending",
    "field_verified_at": null,
    "field_verified_by": null,
    "field_remarks": "Scheduled for joint field visit next week.",
    "compensation_amount": 31420116,
    "compensation_assessed": 31420116,
    "compensation_approved": 0,
    "compensation_paid": 0,
    "payment_status": "Not Assessed",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "Not Started",
    "rehabilitation_amount": 0,
    "rehabilitation_remarks": null,
    "rehabilitation_completed_at": null,
    "latitude": 19.892003,
    "longitude": 74.09584
  },
  {
    "id": "demo-parcel-123",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-123",
    "parcel_no": "SM-NK-123",
    "owner_name": "Navnath Raghunath Dhatrak (DEMO-123)",
    "village_name": "Shivajinagar",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-123/C",
    "survey_no": "SY-123/C",
    "khasra_no": "KHS-SM-123",
    "land_type": "Agricultural",
    "notified_area_sqm": 564338.22,
    "affected_area_sqm": 35224.23,
    "possession_status": "In Progress",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector S. P. Kadam",
    "field_remarks": "Horticulture crop compensation assessed.",
    "compensation_amount": 22895750,
    "compensation_assessed": 22895750,
    "compensation_approved": 22895750,
    "compensation_paid": 0,
    "payment_status": "Approved",
    "payment_reference": null,
    "payment_released_at": null,
    "rehabilitation_status": "In Progress",
    "rehabilitation_amount": 250000,
    "rehabilitation_remarks": "Livelihood assistance in progress.",
    "rehabilitation_completed_at": null,
    "latitude": 19.892163,
    "longitude": 74.1125
  },
  {
    "id": "demo-parcel-124",
    "project_id": "01843f0d-072e-4e25-a0a7-fcd7ed02ea10",
    "project_code": "SM-NASHIK-DEMO-01",
    "parcel_number": "SM-NK-124",
    "parcel_no": "SM-NK-124",
    "owner_name": "Kalyan Bhikaji Pund (DEMO-124)",
    "village_name": "Mundhegaon",
    "taluka_name": "Sinnar Taluka",
    "tehsil": "Sinnar Taluka",
    "district": "Nashik",
    "state": "Maharashtra",
    "survey_number": "SY-124/D",
    "survey_no": "SY-124/D",
    "khasra_no": "KHS-SM-124",
    "land_type": "Residential fringe",
    "notified_area_sqm": 687823.51,
    "affected_area_sqm": 69921.49,
    "possession_status": "Possession Taken",
    "field_verification_status": "Verified",
    "field_verified_at": "2026-08-28T10:00:00Z",
    "field_verified_by": "Inspector V. R. Patil",
    "field_remarks": "Expressway corridor possession taken. Fencing underway.",
    "compensation_amount": 45448969,
    "compensation_assessed": 45448969,
    "compensation_approved": 45448969,
    "compensation_paid": 45448969,
    "payment_status": "Paid",
    "payment_reference": "PFMS-DBT-2026-8023",
    "payment_released_at": "2026-09-01T12:00:00Z",
    "rehabilitation_status": "Completed",
    "rehabilitation_amount": 500000,
    "rehabilitation_remarks": "R&R one-time resettlement allowance credited.",
    "rehabilitation_completed_at": "2026-09-02T16:00:00Z",
    "latitude": 19.901515,
    "longitude": 74.126079
  }
];

export const DEMO_WORKFLOWS: DemoWorkflow[] = [
  {
    "id": "wf-demo-1",
    "project_code": "SM-NASHIK-DEMO-01",
    "workflow_type": "Section 19 - Declaration of Acquisition",
    "stage_name": "Section 19 - Declaration of Acquisition",
    "status": "Approved",
    "assigned_to": "SLAO Nashik Division",
    "submitted_by": "Nashik Division CALA",
    "approved_by": "Competent Authority M. K. Rao, IAS",
    "remarks": "Section 19 statutory declaration gazetted for Samruddhi Nashik corridor.",
    "created_at": "2026-09-05T10:00:00Z",
    "approved_at": "2026-09-08T12:00:00Z"
  },
  {
    "id": "wf-demo-2",
    "project_code": "SM-NASHIK-DEMO-01",
    "workflow_type": "Section 23 - Award Determination",
    "stage_name": "Section 23 - Award Determination",
    "status": "Pending Approval",
    "assigned_to": "SLAO Nashik Division",
    "submitted_by": "SLAO Nashik Division",
    "approved_by": null,
    "remarks": "Comprehensive award enquiry and compensation calculations under review.",
    "created_at": "2026-09-17T11:30:00Z",
    "approved_at": null
  },
  {
    "id": "wf-demo-3",
    "project_code": "NHAI-DEL-BOM-01",
    "workflow_type": "Section 3D - Declaration of Acquisition",
    "stage_name": "Section 3D - Declaration of Acquisition",
    "status": "Approved",
    "assigned_to": "CALA Vadodara & Surat",
    "submitted_by": "Special Land Acquisition Officer",
    "approved_by": "Ministry Nodal Officer A. Sharma",
    "remarks": "Statutory Section 3D declaration gazetted in central portal.",
    "created_at": "2026-08-15T09:00:00Z",
    "approved_at": "2026-08-20T14:00:00Z"
  },
  {
    "id": "wf-demo-4",
    "project_code": "NHAI-NSK-SURCHE",
    "workflow_type": "Section 3A - Intent to Acquire",
    "stage_name": "Section 3A - Intent to Acquire",
    "status": "Approved",
    "assigned_to": "SLAO Dhule / Nashik",
    "submitted_by": "NHAI Project Director",
    "approved_by": "Joint Secretary MoRTH",
    "remarks": "Gazette notification issued under Section 3A of NH Act 1956.",
    "created_at": "2026-08-01T08:00:00Z",
    "approved_at": "2026-08-07T11:00:00Z"
  }
];

export const DEMO_ASSIGNMENTS: DemoAssignment[] = [
  {
    "id": "asg-demo-1",
    "parcel_id": "demo-parcel-101",
    "parcel_number": "SM-NK-101",
    "owner_name": "Eknath Balwantrao Shinde (DEMO-101)",
    "village_name": "Vihigaon",
    "assigned_officer_id": "fo-kadam",
    "assigned_officer_name": "Inspector S. P. Kadam",
    "assigned_officer_email": "field.kadam@morth.gov.in",
    "assigned_at": "2026-08-27T09:00:00Z",
    "status": "Completed",
    "priority": "High",
    "due_date": "2026-08-30",
    "remarks": "Ground boundary verified with highway pegs installed."
  },
  {
    "id": "asg-demo-2",
    "parcel_id": "demo-parcel-105",
    "parcel_number": "SM-NK-105",
    "owner_name": "Kashinath Shivram Gite (DEMO-105)",
    "village_name": "Bharvir Khurd",
    "assigned_officer_id": "fo-patil",
    "assigned_officer_name": "Inspector V. R. Patil",
    "assigned_officer_email": "field.patil@morth.gov.in",
    "assigned_at": "2026-09-10T10:00:00Z",
    "status": "In Progress",
    "priority": "High",
    "due_date": "2026-09-22",
    "remarks": "Verify partition boundary markers with adjacent landholder."
  },
  {
    "id": "asg-demo-3",
    "parcel_id": "demo-parcel-108",
    "parcel_number": "SM-NK-108",
    "owner_name": "Shantabai Madhavrao Dhikale (DEMO-108)",
    "village_name": "Mundhegaon",
    "assigned_officer_id": "fo-kadam",
    "assigned_officer_name": "Inspector S. P. Kadam",
    "assigned_officer_email": "field.kadam@morth.gov.in",
    "assigned_at": "2026-09-15T11:00:00Z",
    "status": "Pending",
    "priority": "Medium",
    "due_date": "2026-09-24",
    "remarks": "Scheduled joint inspection with village Talathi."
  },
  {
    "id": "asg-demo-4",
    "parcel_id": "demo-parcel-111",
    "parcel_number": "SM-NK-111",
    "owner_name": "Chandrakant Motiram Khule (DEMO-111)",
    "village_name": "Wadivarhe",
    "assigned_officer_id": "fo-patil",
    "assigned_officer_name": "Inspector V. R. Patil",
    "assigned_officer_email": "field.patil@morth.gov.in",
    "assigned_at": "2026-09-12T09:30:00Z",
    "status": "In Progress",
    "priority": "High",
    "due_date": "2026-09-21",
    "remarks": "Re-survey irrigation canal offset on southern perimeter."
  },
  {
    "id": "asg-demo-5",
    "parcel_id": "demo-parcel-122",
    "parcel_number": "SM-NK-122",
    "owner_name": "Parvatibai Shankar Tile (DEMO-122)",
    "village_name": "Bharvir Budruk",
    "assigned_officer_id": "fo-kadam",
    "assigned_officer_name": "Inspector S. P. Kadam",
    "assigned_officer_email": "field.kadam@morth.gov.in",
    "assigned_at": "2026-09-16T14:00:00Z",
    "status": "Pending",
    "priority": "Medium",
    "due_date": "2026-09-25",
    "remarks": "Initial boundary pegging and tree inventory required."
  }
];

export const DEMO_OBJECTIONS: DemoObjection[] = [
  {
    "id": "obj-demo-1",
    "parcel_id": "demo-parcel-105",
    "parcel_number": "SM-NK-105",
    "village_name": "Bharvir Khurd",
    "survey_number": "SY-105/A",
    "owner_name": "Kashinath Shivram Gite (DEMO-105)",
    "objection_type": "Land / Parcel Details",
    "description": "Ancestral land partition decree pending before Civil Court; request separate notices for legal heirs.",
    "status": "Under Review",
    "submitted_at": "2026-09-12T11:00:00Z",
    "reviewed_at": "2026-09-14T15:00:00Z",
    "resolved_at": null,
    "reviewer_name": "SLAO Nashik Division",
    "resolution_remarks": "Notice issued to Sub-Divisional Officer for succession certificate verification."
  },
  {
    "id": "obj-demo-2",
    "parcel_id": "demo-parcel-111",
    "parcel_number": "SM-NK-111",
    "village_name": "Wadivarhe",
    "survey_number": "SY-111/C",
    "owner_name": "Chandrakant Motiram Khule (DEMO-111)",
    "objection_type": "Measurement / Area",
    "description": "Field inspection overlap: 850 sqm canal feeder line included in acquisition perimeter.",
    "status": "Under Review",
    "submitted_at": "2026-09-14T09:30:00Z",
    "reviewed_at": "2026-09-16T12:00:00Z",
    "resolved_at": null,
    "reviewer_name": "CALA Nashik",
    "resolution_remarks": "Joint re-survey scheduled with Irrigation Department surveyor."
  },
  {
    "id": "obj-demo-3",
    "parcel_id": "demo-parcel-119",
    "parcel_number": "SM-NK-119",
    "village_name": "Wadivarhe",
    "survey_number": "SY-119/C",
    "owner_name": "Ashok Nivrutti Mogal (DEMO-119)",
    "objection_type": "Compensation",
    "description": "Borewell pump house and commercial drip irrigation lines not included in initial valuation assessment.",
    "status": "Submitted",
    "submitted_at": "2026-09-16T14:15:00Z",
    "reviewed_at": null,
    "resolved_at": null,
    "reviewer_name": null,
    "resolution_remarks": null
  },
  {
    "id": "obj-demo-4",
    "parcel_id": "demo-parcel-102",
    "parcel_number": "SM-NK-102",
    "village_name": "Kasarwadi",
    "survey_number": "SY-102/B",
    "owner_name": "Vishwanath Pandurang Jadhav (DEMO-102)",
    "objection_type": "Compensation",
    "description": "Pomegranate orchard fruit tree valuation reassessment request under Section 29 RFCTLARR Act.",
    "status": "Resolved",
    "submitted_at": "2026-08-20T10:00:00Z",
    "reviewed_at": "2026-08-25T14:00:00Z",
    "resolved_at": "2026-08-28T16:30:00Z",
    "reviewer_name": "Horticulture Evaluation Officer / SLAO",
    "resolution_remarks": "Horticulture department survey approved additional ₹ 4.2L tree compensation; updated in PFMS award."
  }
];

export const DEMO_EVIDENCE: DemoEvidenceDoc[] = [
  {
    "id": "ev-demo-1",
    "parcel_id": "demo-parcel-101",
    "file_name": "SM-NK-101_BoundaryDemarcation_GeoTagged.jpg",
    "file_type": "image/jpeg",
    "file_size_bytes": 2451200,
    "description": "Geo-tagged boundary stone installation at coordinates 19.7699° N, 73.7895° E (Accuracy ±1.2m).",
    "uploaded_by": "Inspector S. P. Kadam",
    "created_at": "2026-08-29T10:35:00Z",
    "category": "Boundary Marker"
  },
  {
    "id": "ev-demo-2",
    "parcel_id": "demo-parcel-101",
    "file_name": "SM-NK-101_JointMeasurementSurvey_Sheet.pdf",
    "file_type": "application/pdf",
    "file_size_bytes": 4120800,
    "description": "Certified Joint Cadastral Survey map signed by SLAO surveyor, Talathi and landholder.",
    "uploaded_by": "Inspector S. P. Kadam",
    "created_at": "2026-08-29T11:00:00Z",
    "category": "Cadastral Survey"
  },
  {
    "id": "ev-demo-3",
    "parcel_id": "demo-parcel-101",
    "file_name": "SM-NK-101_PFMS_DBT_PaymentReceipt.pdf",
    "file_type": "application/pdf",
    "file_size_bytes": 845000,
    "description": "PFMS Direct Benefit Transfer confirmation receipt: UTR PFMS-DBT-2026-8000 for ₹ 1,29,79,577.",
    "uploaded_by": "PFMS Treasury Integration",
    "created_at": "2026-09-01T14:20:00Z",
    "category": "DBT Receipt"
  },
  {
    "id": "ev-demo-4",
    "parcel_id": "demo-parcel-102",
    "file_name": "SM-NK-102_PomegranateOrchard_ValuationReport.pdf",
    "file_type": "application/pdf",
    "file_size_bytes": 3105000,
    "description": "District Horticulture Department tree valuation certificate under Section 29.",
    "uploaded_by": "Inspector S. P. Kadam",
    "created_at": "2026-08-26T15:10:00Z",
    "category": "Tree Valuation"
  },
  {
    "id": "ev-demo-5",
    "parcel_id": "demo-parcel-101",
    "file_name": "Gazette_Notification_Sec3A_SamruddhiNashik.pdf",
    "file_type": "application/pdf",
    "file_size_bytes": 1890000,
    "description": "Official Gazette of India Section 3A notification for Mumbai–Nagpur Samruddhi Expressway.",
    "uploaded_by": "Ministry of Road Transport & Highways",
    "created_at": "2026-07-15T09:00:00Z",
    "category": "Gazette Notice"
  }
];

export function getDemoKpis(projectCode: string = 'SM-NASHIK-DEMO-01') {
  if (projectCode === 'ALL') {
    return {
      totalProjects: DEMO_PROJECTS.length,
      totalNotifiedAreaHa: 15901.4,
      areaAcquiredHa: 1845.2,
      acquiredPercentage: 12,
      compensationDisbursedCrores: 486.5,
      affectedFamiliesCount: 540,
      rehabilitatedFamiliesCount: 182,
      rehabilitatedPercentage: 34,
      activeProjectsCount: 4,
      reviewProjectsCount: 1,
      draftProjectsCount: 1,
    }
  }

  const selectedProj = DEMO_PROJECTS.find((p) => p.project_code === projectCode) || DEMO_PROJECTS[0]
  const relevantParcels = DEMO_PARCELS.filter((p) => p.project_code === projectCode)

  const ACQUIRED_SET = new Set(['Possessed', 'Possession Taken', 'Acquired', 'Completed'])
  const acquiredParcels = relevantParcels.filter((p) => ACQUIRED_SET.has(p.possession_status))
  const acquiredSqm = acquiredParcels.reduce((sum, p) => sum + (p.affected_area_sqm || p.notified_area_sqm || 0), 0)
  const totalPaid = relevantParcels.reduce((sum, p) => sum + (p.compensation_paid || 0), 0)
  const uniqueOwners = new Set(relevantParcels.map((p) => p.owner_name.trim())).size
  const rehabCompleted = relevantParcels.filter((p) => p.rehabilitation_status === 'Completed').length

  const totalNotifiedHa = selectedProj.total_area_required_ha || 97.48
  const areaAcquiredHa = acquiredSqm / 10000
  const acquiredPercentage = totalNotifiedHa > 0 ? Math.min(100, Math.round((areaAcquiredHa / totalNotifiedHa) * 100)) : 0

  return {
    totalProjects: 1,
    totalNotifiedAreaHa: totalNotifiedHa,
    areaAcquiredHa: parseFloat(areaAcquiredHa.toFixed(2)),
    acquiredPercentage,
    compensationDisbursedCrores: parseFloat((totalPaid / 10000000).toFixed(2)),
    affectedFamiliesCount: uniqueOwners,
    rehabilitatedFamiliesCount: rehabCompleted,
    rehabilitatedPercentage: uniqueOwners > 0 ? Math.round((rehabCompleted / uniqueOwners) * 100) : 0,
    activeProjectsCount: 1,
    reviewProjectsCount: 0,
    draftProjectsCount: 0,
  }
}
